### ISSUE TITLE
Fix your leak nn

### ISSUE THREAD

**Issue by editmedev** [CoolClientCollectors/editme-release#1]
![Capture](https://user-images.githubusercontent.com/67233586/85228578-68c6dd00-b3e4-11ea-8390-2ea7d0b96a6a.PNG)
![Capture1](https://user-images.githubusercontent.com/67233586/85228580-6bc1cd80-b3e4-11ea-96c8-868e4646d9da.PNG)
![Capture2](https://user-images.githubusercontent.com/67233586/85228583-6cf2fa80-b3e4-11ea-8f83-e075965aefb4.PNG)
![Capture3](https://user-images.githubusercontent.com/67233586/85228584-6ebcbe00-b3e4-11ea-8bf8-f532ff5868ff.PNG)
![Capture4](https://user-images.githubusercontent.com/67233586/85228587-72e8db80-b3e4-11ea-8573-1c99da36e7ea.PNG)
![Capture5](https://user-images.githubusercontent.com/67233586/85228590-741a0880-b3e4-11ea-88b2-dcc19daf6dad.PNG)

**Comment by Tigermouthbear** [comment]
seems like an edit me problem

**Comment by editmedev** [comment]
Than how come everyone was praising the actual ca?
And why are so many modules missing?

![ca1](https://user-images.githubusercontent.com/67233586/85228798-01119180-b3e6-11ea-9532-549b965f4048.PNG)
![ca2](https://user-images.githubusercontent.com/67233586/85228799-01aa2800-b3e6-11ea-980f-dee3401800ae.PNG)

**Comment by Tigermouthbear** [comment]
idk it's ur client bro

**Comment by Crystallinqq** [comment]
nice job telling ur own users to call it bad :/

**Comment by x4e** [comment]
Sounds like a u problem
