### ISSUE TITLE
Blatant virus for not-crack and cracked, CryptInject!ml. It so clear that it's not legit lmaoooo.

### ISSUE THREAD

**Issue by me-rgb** [CoolClientCollectors/editme-release#3]

**Comment by me-rgb** [comment]
Also btw is a Backdoor (Bladabindi!ml) and this gives it remote access to the computer it is installed on. It would be nice if you TRIED to hide it but it is RIGHT there lmao

**Comment by Crystallinqq** [comment]
shit bait

**Comment by me-rgb** [comment]
![Explain](https://user-images.githubusercontent.com/56459146/102231669-3641fc80-3ebc-11eb-8000-457979d16b81.PNG)
Explain then

**Comment by me-rgb** [comment]
hahaha I found 1 more virus in non-cracked and 1 more in cracked (All: Trojan:Win32/CryptInject!ml Backdoor:Win32/Bladabindi!ml VirTool:Win32/Atosev!ml Program:Win32/Uwasson.A!ml)

**Comment by Crystallinqq** [comment]
all from obfuscation stfu

**Comment by ghost** [comment]
> all from obfuscation stfu

LOLOLOLOLOL
